Add "remote" debug option of json file
Meliox/PVE-mods pull request #50
Opened 2024-06-12 18:03 UTC by Meliox

2024-06-15 10:54 UTC, eremem requested changes
Please take a look at the patch I attached: [0001-Adjust-boolean-expressions.patch](https://github.com/user-attachments/files/15846526/0001-Adjust-boolean-expressions.patch).
*I never used this function in GitExtensions (my git client) and I am not sure if it's a regular patch file. If not, please try to apply these few changes manually.*

My suggested changes address the following points:
- consistent handling of boolean variables:
please compare DEBUG_REMOTE  vs. e.g. sensorsDetected or enableHddTemp
- loading the sensors readings from a dump file: 
I see that the Perl code you inject for the debug mode is quite complex. I used a much simpler approach before and just changed a single line in Nodes.pm after a "normal" installation:
`$res->{sensorsOutput} = `sensors -j`;`
to
`$res->{sensorsOutput} = cat "/tmp/sensordata.json";`
Even if the dump file will be removed after the installation, the only side-effect in the UI will be a bunch of "N/A"s. The debug mode is not meant for users anyway, so the impact in such a case will only be limited to us;)

2024-06-15 17:13 UTC, Meliox commented
Thanks for the review. I have addressed the changes and rebased to main :)

2024-06-16 07:52 UTC, Meliox commented
@eremem: Can you approve the changes?

2024-06-16 09:41 UTC, eremem approved these changes

2024-06-16 09:42 UTC, merged